### ISSUE TITLE
Imagenes pixeladas

### ISSUE THREAD

**Issue by earias08** [MarianaReid/Proyecto3_frontEnd#49]
## Proceso
Ingresando a la pagina principal en dispositivos medianos y grandes.

## Resultado esperado
Visualizar las imagenes correctamente.

## Resultado actual
La imagen principal se visualiza pixelada
La imagen principal tiene texto que no se visualiza correctamente

## Captura
![image](https://user-images.githubusercontent.com/18445151/225938307-1e5b58ee-aeec-40bb-a14c-68370160883c.png)

## Sugenencia

Buscar imagenes de buena calidad sin texto, en paginas como [pexel](https://www.pexels.com/es-es/)

**Comment by eOrrego** [comment]
Se crea file css para correcciones de ese issue

![image](https://user-images.githubusercontent.com/2162499/226151034-f0a41b77-ff97-4970-b28d-7119c46e4495.png)
