### ISSUE TITLE
Espacio en footer

### ISSUE THREAD

**Issue by earias08** [MarianaReid/Proyecto3_frontEnd#50]
## Proceso
Al ingresar a todas las paginas

## Resultado esperado
Visualizar correctamente la información del footer.

## Resultado actual
El titulo contacto del footer esta pegado a la linea del footer, en dispositivos medianos y grandes 

## Captura

![image](https://user-images.githubusercontent.com/18445151/225939778-31e891c9-c073-4bf5-a787-3b2f5d0884bf.png)

**Comment by eOrrego** [comment]
se realiza correccion en componente footer

![image](https://user-images.githubusercontent.com/2162499/226151828-c74c181e-3835-49f8-8b20-c5f812e42f9a.png)

![image](https://user-images.githubusercontent.com/2162499/226151830-47acabb4-6a59-46a6-9019-5914bdbe41f3.png)
