### ISSUE TITLE
Corregir cards con imagenes de productos

### ISSUE THREAD

**Issue by earias08** [MarianaReid/Proyecto3_frontEnd#51]
## Proceso
Al ingresar a la pagina principal en dispositivos pequeños, medianos y grandes

## Resultado esperado
Visualizar las cards en tamaños iguales
Las imagenes dentro de las cards no deben exceder al contenedor.

## Resultado actual
Las cards tienen tamaños diferentes.
Algunas imagenes quedan fuera de la card.

## Captura
![image](https://user-images.githubusercontent.com/18445151/225940737-7d4782e5-4cc0-45ba-a2b3-5fa5a4801184.png)

**Comment by eOrrego** [comment]
Se realiza corrección agregando file css. para home y layoutPublic.

![image](https://user-images.githubusercontent.com/2162499/226181968-055b3790-4489-48cf-91d2-6aec5aa1d710.png)
![image](https://user-images.githubusercontent.com/2162499/226181972-30e4baea-2cd4-4463-a0b3-07417f65ebb5.png)
