### ISSUE TITLE
Opciones de administrador extras

### ISSUE THREAD

**Issue by earias08** [MarianaReid/Proyecto3_frontEnd#54]
## Proceso
Al ingresar a la pagina de administrador en la lista de usuarios

## Resultado esperado
Se espera poder visualizar los usuarios, con sus opciones para agregar, editar y borrar un usuario

## Resultado actual
Ademas del botón editar, hay dos botoner (I) y (A) que actualizan la pagina y muestran el mensaje de usuario editado

## Captura
![image](https://user-images.githubusercontent.com/18445151/225945536-16e7e7ff-6203-48cb-95ae-647c1e8d706f.png)

**Comment by eOrrego** [comment]
En este caso el boton I o A era para manejar el estado del user, Activo o inactivo.
Se realizo la correccion agregando en el formulario

![image](https://user-images.githubusercontent.com/2162499/226365623-1702f236-bd26-414a-a9a5-a68ed9997edb.png)
