### ISSUE TITLE
Actualizar los datos de la tabla pedidos al cambiar su estado

### ISSUE THREAD

**Issue by earias08** [MarianaReid/Proyecto3_frontEnd#56]
## Proceso
Al ingresar a la tabla para administrar los pedidos y seleccionar el botón (p) para actualizar el estado del pedido.

## Resultado esperado
Mostrar un cartel de actualizacion del estado del pedido, al presionar ok en el cartel visualizar la tabla actualizada.

## Resultado actual
Se muestra el cartel de estado de pedido actualizado, al presionar ok en el cartel la tabla no se actualiza. Hay que ir actualizar la pagina para visualizar los datos actualizados.

## Captura
![image](https://user-images.githubusercontent.com/18445151/225949592-c604ff7d-cf32-4bbb-b645-a8e9da8296a4.png)
![image](https://user-images.githubusercontent.com/18445151/225949674-99d8eb75-93d8-4ef7-8423-56a99c019575.png)

**Comment by eOrrego** [comment]
Se refactoriza y se implementa pagina de detalles de carrito, en ese lugar se completa el pedido.

![image](https://user-images.githubusercontent.com/2162499/226498891-8a3ae79a-b82e-475f-ad75-64ccad866738.png)
